### ISSUE TITLE
Support tearing down the network

### ISSUE THREAD

**Issue by ldesrosi** [IBM-Blockchain/ansible-role-blockchain-platform-manager#43]
It would be good if the scripts could also support the cleanup of the network.  Particularly interesting for CI/CD use cases.  Ideally for both Docker and IBM Blockchain Platform.

**Comment by sstone1** [comment]
The standard Ansible way for this is to have a `state` parameter, and perform the right action based on the current state and the desired state (e.g. `present`, `absent`, `stopped`).

**Comment by ldesrosi** [comment]
Correct.  However, this has to be added to the playbook and needs to make its way to the tasks. 

Something like:
```
      - &Org2
        msp:
          id: "Org2MSP"
          admin:
            identity: "org2Admin"
            secret: "org2Adminpw"
          ibp:
            display_name: "Org2 MSP"
          state: absent
```

which results in the deletion of the MSP and all underlying infra? (CA, Peers, etc...)?
